### ISSUE TITLE
Does not seem to understand the Kasa HS300 power strips

### ISSUE THREAD

**Issue by luckyyvt** [jeffkowalski/kasa#1]
I can see it discovers my singular Kasa devices like power switches, and single outlets properly.  But when it walks the HS300 power strips, it throws an exception "unexpected token" error.

I suspect it does not understand how to read the multiple (6 outlets) meter entries that are returned by those devices.  Attached is a log file dump of the resulting error.

[log_clip.txt](https://github.com/jeffkowalski/kasa/files/8254010/log_clip.txt)

If there is anything more I can provide, logs, etc., I'd be happy to, thanks!

**Comment by jeffkowalski** [comment]
Thanks for sending in the report and including the log.  I've addressed the root cause.  Give it another shot.  Hope you're finding the code useful in your project.

**Comment by luckyyvt** [comment]
Jeff,

Thanks that worked perfectly this time.  However, it is not parsing out the
energy meter data, only the state of the outlet (on or off).   I would like
to collect the emeter information into Influx too, it does that for my
singular Kasa outlets, but the strips it is just showing the state
information in the database.

Attached is the new log, and it is showing some of the meter data, although
it seems to be maybe for just one port, or perhaps is a summary of all
ports together and not data for each port.

For example if I query the HS300 strip with the Python library "pyhs100"
tool, it will return something like this for the emeter query, showing
ports 0-5 (it is a 6 outlet strip) and the power on each outlet.
== Current State ==
{0: {'voltage_mv': 119234, 'current_ma': 399, 'power_mw': 46075,
'total_wh': 2135}, 1: {'voltage_mv': 119085, 'current_ma': 4, 'power_mw':
17, 'total_wh': 0}, 2: {'voltage_mv': 119217, 'current_ma': 4, 'power_mw':
36, 'total_wh': 0}, 3: {'voltage_mv': 119135, 'current_ma': 4, 'power_mw':
17, 'total_wh': 0}, 4: {'voltage_mv': 119300, 'current_ma': 4, 'power_mw':
0, 'total_wh': 0}, 5: {'voltage_mv': 119234, 'current_ma': 19, 'power_mw':
1649, 'total_wh': 82}}

Hope that is helpful, thanks for a great little util!

**Comment by jeffkowalski** [comment]
Would you kindly open up another (separate) issue, and I'll have a look?
Thanks,
Jeff
